### ISSUE TITLE
TypeError: Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by luizjunior** [arnif/homebridge-sony-television#4]
After updating to iOS 12.2, homebridge is crashing with the following error:

/usr/lib/node_modules/homebridge-sony-television/index.js:149
      var result = response.result;
                            ^

TypeError: Cannot read property 'result' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-sony-television/index.js:149:29)
    at self.callback (/usr/lib/node_modules/homebridge-sony-television/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-sony-television/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:180:13)
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)

**Comment by luizjunior** [comment]
Printing the err variable at index.js:149:

{ Error: getaddrinfo ENOTFOUND undefined undefined:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  message: 'getaddrinfo ENOTFOUND undefined undefined:80',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined',
  host: 'undefined',
  port: 80 }

**Comment by luizjunior** [comment]
Never mind, it was just a typo at accessories section.

Also, will be nice if you add at index.js:149
	if (err){
		console.log(err);
		return;
	}

cheers!

**Comment by arnif** [comment]
is the `ipaddress` correct in your `config.js` file ?

**Comment by luizjunior** [comment]
> is the `ipaddress` correct in your `config.js` file ?

I've replied above.
