### ISSUE TITLE
When a TV is disconnected from the network, homebridge crashes

### ISSUE THREAD

**Issue by janthony6** [arnif/homebridge-sony-television#5]
Driver has been working great.  I sold a TV and before I removed it from homebridge, I disconnected the ethernet and power from the tv.  This resulted in completely crashing homebridge and making all of my 51 devices go to "No response."  This is the error from the log:

TypeError: Cannot read property 'result' of undefined
at Request._callback (/usr/lib/node_modules/homebridge-sony-television/index.js:149:29)
at self.callback (/usr/lib/node_modules/homebridge-sonytelevision/node_modules/request/request.js:185:22)
at Request.emit (events.js:197:13)
at Request.onRequestError (/usr/lib/node_modules/homebridge-sonytelevision/node_modules/request/request.js:881:8)
at ClientRequest.emit (events.js:197:13)
at Socket.socketErrorListener (_http_client.js:399:9)
at Socket.emit (events.js:197:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by arnif** [comment]
and was it not solved after you removed the accessory from the `config.json` file ?

the culprit is here: https://github.com/arnif/homebridge-sony-television/blob/master/index.js#L149

**Comment by kontur11** [comment]
The same problem, but the network is not lost

**Comment by arnif** [comment]
is the `ipaddress` correct  in the config?

**Comment by kontur11** [comment]
Yes, everything worked

**Comment by arnif** [comment]
So if I patch the error, another one will just come up I suspect. The TV is not responding with any data. Homebridge is not able to talk to the TV for some reason. If you disconnected the TV and remove the accessory from the config I would assume Homebridge should remove the accessory from HomeKit but maybe its being cached somewhere ? You could try to delete the `accessories` folder under `~/.homebridge` but I would not recommend that if you have multiple accessories (might need to assign them to rooms again etc). Maybe there is a way to clear the cache somehow ?

**Comment by janthony6** [comment]
I dont think you understand what is happening.  

Everything works fine as long as the network is up.  If a tv is ever disconnected though, like if the wire is unplugged or the switch gets an update and reboots, an error happens that stops all devices on the homebridge from working.

Test by unplugging your network cable to your tv.  In HomeKit only the tv should show not responding, however instead it crashes all of the HomeKit devices. 

Thanks,
Jason

**Comment by arnif** [comment]
I added check for the response before checking it. I don't have access to Sony tv at the moment so feel free to try it (version 0.0.4)
